import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppinsRegular = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-neutral-100 text-slate-700">
      <body className={poppinsRegular.className}>{children}</body>
    </html>
  );
}
