// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternate_hero: dynamic(() => import("./AlternateHero")),
  animated_headings: dynamic(() => import("./AnimatedHeadings")),
  animated_text: dynamic(() => import("./AnimatedText")),
  biography: dynamic(() => import("./Biography")),
  case_study: dynamic(() => import("./CaseStudy")),
  contact: dynamic(() => import("./Contact")),
  content_index: dynamic(() => import("./ContentIndex")),
  experience: dynamic(() => import("./Experience")),
  hero: dynamic(() => import("./Hero")),
  tech_list: dynamic(() => import("./Skills")),
  text_block: dynamic(() => import("./TextBlock")),
};
